version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
    - npm run package-win
    - npm run create-installer-win
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./release-builds
