version: 0.2

phases:
  install:
    commands:
      npm install -g electron-forge
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - mkdir .build
      - cd .build
      - electron-forge import ../
      - y
      - n
      - electron-forge package
      - electron-forge make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.js
