version: 0.2

phases:
  install:
    commands:
      - apt-get install --no-install-recommends expect
      - npm install -g electron-forge
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - mkdir .build
      - cd .build
      - ../electron-import.sh
      - electron-forge package
      - electron-forge make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.js
